//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawfect.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PetCareEntities : DbContext
    {
        public PetCareEntities()
            : base("name=PetCareEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Adoption> Tbl_Adoption { get; set; }
        public virtual DbSet<Tbl_Doctor> Tbl_Doctor { get; set; }
        public virtual DbSet<Tbl_Donation> Tbl_Donation { get; set; }
        public virtual DbSet<Tbl_MedicalAssistance> Tbl_MedicalAssistance { get; set; }
        public virtual DbSet<Tbl_Pets> Tbl_Pets { get; set; }
        public virtual DbSet<Tbl_Products> Tbl_Products { get; set; }
        public virtual DbSet<Tbl_purchased_products> Tbl_purchased_products { get; set; }
        public virtual DbSet<Tbl_Query> Tbl_Query { get; set; }
        public virtual DbSet<Tbl_User> Tbl_User { get; set; }
    }
}
