//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawfect.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Tbl_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_User()
        {
            this.Tbl_Adoption = new HashSet<Tbl_Adoption>();
            this.Tbl_MedicalAssistance = new HashSet<Tbl_MedicalAssistance>();
            this.Tbl_purchased_products = new HashSet<Tbl_purchased_products>();
            this.Tbl_Query = new HashSet<Tbl_Query>();
        }
        [Required(ErrorMessage = "UserID must be filled")]
        public int UserID { get; set; }

        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string UserPassword { get; set; }

        [NotMapped]
        [Required]
        [Compare("UserPassword",ErrorMessage ="Password mismatch")]
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }

        [Required]
        [StringLength(13, ErrorMessage = "Phone number should be in 10 digits", MinimumLength = 10)]
        public string Phone_No { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        public string UserAddress { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }
       
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Adoption> Tbl_Adoption { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MedicalAssistance> Tbl_MedicalAssistance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_purchased_products> Tbl_purchased_products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Query> Tbl_Query { get; set; }
    }
}
