//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawfect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Adoption
    {
        public int AdoptionID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> PetID { get; set; }
    
        public virtual Tbl_Pets Tbl_Pets { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
