//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawfect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Donation
    {
        public int DonorID { get; set; }
        public string Donor_Name { get; set; }
        public string Donation_Amount { get; set; }
        public string DonorAddress { get; set; }
        public string ContactNo { get; set; }
    }
}
