//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawfect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Pets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Pets()
        {
            this.Tbl_Adoption = new HashSet<Tbl_Adoption>();
        }
    
        public int PetID { get; set; }
        public string Pet_Category { get; set; }
        public string Age { get; set; }
        public string Pet_Breed { get; set; }
        public string Sex { get; set; }
        public string Height { get; set; }
        public string Weights { get; set; }
        public string Colour { get; set; }
        public string Pet_Price { get; set; }
        public string ImageLocation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Adoption> Tbl_Adoption { get; set; }
    }
}
