//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawfect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MedicalAssistance
    {
        public int Medical_id { get; set; }
        public Nullable<int> UserID { get; set; }
        public string petID { get; set; }
        public string Problem { get; set; }
        public Nullable<System.DateTime> Date_Of_Appointment { get; set; }
        public Nullable<System.TimeSpan> Time_Of_Appointment { get; set; }
        public Nullable<int> DoctorId { get; set; }
    
        public virtual Tbl_Doctor Tbl_Doctor { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
