//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAWFETNEW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class animals1
    {
        public int id { get; set; }
        public Nullable<int> ranking { get; set; }
        public Nullable<int> pet_id { get; set; }
    
        public virtual Tbl_Pets Tbl_Pets { get; set; }
        public virtual Tbl_Pets Tbl_Pets1 { get; set; }
    }
}
