//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//#define AdminName "Admin"
//#define NAME [TechOnTheNet.com]


namespace PAWFETNEW.Models
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;

    public partial class Tbl_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_User()
        {
            this.Tbl_Adoption = new HashSet<Tbl_Adoption>();
            this.Tbl_DayCare = new HashSet<Tbl_DayCare>();
            this.Tbl_MedicalAssistance = new HashSet<Tbl_MedicalAssistance>();
            this.Tbl_Service_Offered = new HashSet<Tbl_Service_Offered>();
        }

        [NotMapped]
        public int UserID { get; set; }
        [Required(ErrorMessage = "**Required")]
        [Display(Name = "Name")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "**Required")]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        [RegularExpression(@"(?=.*\d)(?=.*[A-Za-z]).{5,}", ErrorMessage = "Use even more strong Password(Eg-India1997)")]
        public string UserPassword { get; set; }

        [NotMapped]
        [Required(ErrorMessage = "**Required")]
        [System.ComponentModel.DataAnnotations.Compare("UserPassword", ErrorMessage = "Password mismatch")]
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }

        [Required(ErrorMessage = "**Required")]
        [RegularExpression(@"^[0-9]{10}$", ErrorMessage = "Contact Number should be numeric and should be 10 digit ")]
        [DataType(DataType.PhoneNumber)]
        //[StringLength(10, ErrorMessage = "Contact Number should be in 10 digits", MinimumLength = 10)]
        [Display(Name = "Contact Number")]
        public string Phone_No { get; set; }

        [Required(ErrorMessage = "**Required")]
        [DataType(DataType.MultilineText)]
        [Display(Name = "Address")]
        public string UserAddress { get; set; }

        [Required(ErrorMessage = "**Required")]
        [EmailAddress]
        [RemoteAttribute("IsUserExist", "LoginAndRegister", ErrorMessage = "Email id aldready exists.")]
        [Display(Name = "EmailID")]


        public string Email { get; set; }
        [NotMapped]
        public string AdminMail = "admin@gmail.com";
        [NotMapped]
        public string AdminPassword = "newuser123#";
        [NotMapped]
        public string AdminName = "admin";

        [DataType(System.ComponentModel.DataAnnotations.DataType.Date)]
        [NotMapped]
        public string date { get; set; }

        public int Wallet { get; set; }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Adoption> Tbl_Adoption { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_DayCare> Tbl_DayCare { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MedicalAssistance> Tbl_MedicalAssistance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Service_Offered> Tbl_Service_Offered { get; set; }
    }
}
