//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAWFETNEW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Service_Offered
    {
        public int Offer_id { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ServiceId { get; set; }
    
        public virtual Tbl_Service Tbl_Service { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
