//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAWFETNEW.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_Donation
    {
        public int DonorID { get; set; }
        [Required(ErrorMessage = "**Required")]
        [Display(Name ="Name")]
        public string Donor_Name { get; set; }
        [Display(Name = "Amount")]
        [Required(ErrorMessage = "**Required")]
        public string Donation_Amount { get; set; }
        [Required(ErrorMessage = "**Required")]
        [Display(Name = "Address")]
        [DataType(DataType.MultilineText)]
        public string DonorAddress { get; set; }
        [RegularExpression(@"^[0-9]{10}$", ErrorMessage = "Contact Number should be numeric and should be 10 digit ")]
        [DataType(DataType.PhoneNumber)]
        [Required(ErrorMessage = "**Required")]
        
        public string ContactNo { get; set; }
        [Required(ErrorMessage = "**Required")]
        [Display(Name = "Date")]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Date)]
        public Nullable<System.DateTime> donation_date { get; set; }

    }
}
