//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAWFETNEW.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_DayCare
    {
        public int Daycare_id { get; set; }
        public Nullable<int> UserID { get; set; }
        [Required(ErrorMessage = "**Required")]
        public string PetCategory { get; set; }
        [Required(ErrorMessage = "**Required")]
        public string PetBreed { get; set; }
        [Required(ErrorMessage = "**Required")]
        [Display(Name = "Date Of Service")]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Date)]
        public Nullable<System.DateTime> Date_Of_Service { get; set; }
        [Required(ErrorMessage = "**Required")]
        public string Duration { get; set; }
        [Required(ErrorMessage = "**Required")]
        [Display(Name = "Service Name")]
        public Nullable<int> Service_id { get; set; }


        public virtual Tbl_Service Tbl_Service { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
